### ISSUE TITLE
Does this tree support search functionality like search for a text in the tree?

### ISSUE THREAD

**Issue by mtskm** [oxyno-zeta/react-editable-json-tree#3]

**Comment by oxyno-zeta** [comment]
Hello,

No there is no search functionality. But you can create it I think.
An idea can be:
- create a input in which you type the searched text.
- create a getStyle function that highlight searched text and/or to not display keys that doesn't have the searched key.
- create a isCollapse that open node that have the searched text. 

I haven't tested this. This can maybe not work.

Feel free to create a pull request to add this in the library.

Oxyno-zeta

**Comment by mtskm** [comment]
Thank you, got the isCollapse working. But isCollapse method is invoked only once and it does not get invoked every time based on search text.

**Comment by mtskm** [comment]
isCollapsed method is not invoked every time tree is rendered? Any reasons why? Whereas getStyle is invoked all the time tree is rerendered.

**Comment by mtskm** [comment]
isCollapsed method is not invoked every time tree is rendered? Any reasons why? Whereas getStyle is invoked all the time tree is rerendered.

**Comment by oxyno-zeta** [comment]
I forgot this point.
Yes the isCollapsed function is only called in component constructor. Why ? Because this function is here to expand/collapse node the first time. After, you can change this by clicking on node.
If I change to expand/collapse on render, the property cannot change (expect if you have a count in your function).
So, sorry but I don't see how to change this behaviour.
